[build]
  command = "npm install --prefix netlify/functions && cd client && npx vite build"
  publish = "client/dist"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
